// Data for Relevant Experience section of Resume page
export const resumeRelevantExp = [
  {
    company: "Enterprise Rent-A-Car",
    location: "Dayton, OH - Denver, CO",
    title: "Assistant Branch Manager",
    startDate: "2016",
    endDate: "2020",
    achievements: [
      {
        description: `Strategically expanded the flagship branch fleet from 250 to 500 vehicles, while maintaining a 96% utilization rate, propelling the branch to the top in profitability across Ohio, Indiana, and Kentucky`,
        relatedSkills: [
          `communication`,
          `leadership`,
          `problem-solving`,
          `creativity`,
          `adaptability`,
          `self-learning`,
          `algorithmic-thinking`,
          `time-management`,
          `project-management`,
        ],
      },
      {
        description: `Achieved a historic 98 ESQi (Enterprise Service Quality index), the highest customer service score in Midwest Group's history for a flagship branch, and successfully mentored over 15 employees for promotion to management roles within a year`,
        relatedSkills: [
          `communication`,
          `leadership`,
          `problem-solving`,
          `creativity`,
          `adaptability`,
          `self-learning`,
          `team-building`,
          `emotional-intelligence`,
          `teamwork-and-collaboration`,
          `time-management`,
        ],
      },
      {
        description: `Excelled as the premier Assistant Manager in the Midwest Group by crafting and executing tailored marketing strategies, leveraging team strengths to enhance corporate account relations and performance`,
        relatedSkills: [
          `communication`,
          `critical-thinking`,
          `creativity`,
          `initiative`,
          `time-management`,
          `project-management`,
          `attention-to-detail`,
          `researching`,
          `data-analysis`,
          `data-visualization`,
        ],
      },
      {
        description: `Voluntarily transferred to the lowest-performing branch in Colorado to showcase management skills; successfully raised customer service score (ESQi) by 15 points and increased operating profit by 20% within two months`,
        relatedSkills: [
          `communication`,
          `leadership`,
          `critical-thinking`,
          `problem-solving`,
          `creativity`,
          `adaptability`,
          `self-learning`,
          `algorithmic-thinking`,
          `Initiative`,
          `emotional-intelligence`,
          `teamwork-and-collaboration`,
          `self-motivation`,
          `project-management`,
          `attention-to-detail`,
        ],
      },
      {
        description: `Exemplified outstanding leadership by steering a dynamic team of over 30 professionals, overseeing comprehensive branch operations with a steadfast commitment to industry best practices and operational excellence`,
        relatedSkills: [
          `communication`,
          `leadership`,
          `critical-thinking`,
          `problem-solving`,
          `creativity`,
          `adaptability`,
          `self-learning`,
          `algorithmic-thinking`,
          `initiative`,
          `team-building`,
          `emotional-intelligence`,
          `teamwork-and-collaboration`,
          `time-management`,
          `project-management`,
          `data-analysis`,
          `data-visualization`,
        ],
      },
    ],
  },
  {
    company: "Symmetry Financial Group",
    location: "Denver, CO",
    title: "Life Insurance Agent",
    startDate: "2021",
    endDate: "2023",
    achievements: [
      {
        description: `Fostered strong client relationships leading to a high referral rate, averaging 12 referral appointments weekly, placing in the top 95th percentile`,
        relatedSkills: [
          `communication`,
          `initiative`,
          `emotional-intelligence`,
          `self-motivation`,
          `time-management`,
        ],
      },
      {
        description: `Conducted monthly live sales call training sessions, sharing expertise and best practices with new hires to enhance objection handling and ethical sales processes`,
        relatedSkills: [
          `communication`,
          `leadership`,
          `creativity`,
          `adaptability`,
          `self-learning`,
          `initiative`,
          `team-building`,
          `emotional-intelligence`,
          `teamwork-and-collaboration`,
          `time-management`,
        ],
      },
      {
        description: `Innovated sales techniques, including personalized mortgage amortization schedules, to facilitate 'One-Call-Closes,' culminating in an average of over $1 million in monthly policy sales`,
        relatedSkills: [
          `communication`,
          `critical-thinking`,
          `problem-solving`,
          `creativity`,
          `adaptability`,
          `self-learning`,
          `algorithmic-thinking`,
          `initiative`,
          `emotional-intelligence`,
          `self-motivation`,
          `researching`,
          `data-analysis`,
          `data-visualization`,
        ],
      },
    ],
  },
];
